report/urls.py
from django.urls import path

from .views import (
    SendReportView, TasksView, ReportsView,
    pdf_task_view, report_view, pdf_report_view, reports_comparator_view,
)

urls = [
    path('', SendReportView.as_view(), name='send_report'),
    path('reports/', ReportsView.as_view(), name='reports'),
    path('tasks/', TasksView.as_view(), name='tasks'),
    path('task/<int:tid>/', pdf_task_view, name='task'),
    path('report/<int:rid>/', report_view, name='report'),
    path('report/<int:rid>/pdf/', pdf_report_view, name='pdf_report'),
    path('report/comparator/<int:tid>/', reports_comparator_view, name='reports_comparator'),
]

reports_generator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, reverse_lazy, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView

from report.urls import urls

urlpatterns = [
    path('', include(urls)),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    path('password-change/', PasswordChangeView.as_view(
        success_url=reverse_lazy('send_report'),
        template_name='report/password_change.html'
    ), name='password-change'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/models.py
from collections import OrderedDict

from django.contrib.auth.models import User
from django.db import models
from django.db.models import QuerySet
from django.urls import reverse
from django.utils import timezone


class GoogleApiFolder(models.Model):
    title = models.CharField(verbose_name='Title', max_length=64)
    api_id = models.CharField(verbose_name='Google drive folder ID', max_length=128)

    class Meta:
        ordering = 'title',

    def __str__(self) -> str:
        return self.title


class Group(models.Model):
    title = models.CharField(verbose_name='Title', max_length=32, db_index=True)
    folder = models.ForeignKey(
        GoogleApiFolder, on_delete=models.SET_NULL, null=True, blank=True,
        verbose_name='Google drive folder with group data'
    )
    users = models.ManyToManyField(User, related_name='student_groups',
                                   verbose_name='Users', blank=True)

    class Meta:
        ordering = 'title',

    @property
    def users_count(self) -> int:
        return self.users.count()

    def __str__(self) -> str:
        return self.title


class Task(models.Model):
    number = models.IntegerField(verbose_name='Number')
    title = models.CharField(verbose_name='Title', max_length=128)
    description = models.TextField(verbose_name='Description')
    enabled = models.BooleanField(verbose_name='Enabled', default=True)

    @property
    def name(self) -> str:
        return f'{self.number}. {self.title}'

    @classmethod
    def get_enabled(cls) -> QuerySet['Task']:
        return cls.objects.filter(enabled=True)

    class Meta:
        ordering = 'number', 'title',

    def get_absolute_url(self) -> str:
        return reverse('task', args=(self.id,))

    def __str__(self) -> str:
        return self.name


def task_file_path(task_file: 'TaskFile', filename: str) -> str:
    ext = filename.rsplit('.', 1)[-1]
    return f'tasks/{task_file.task.name}.{ext}'


class TaskFile(models.Model):
    task = models.OneToOneField(Task, on_delete=models.CASCADE,
                                verbose_name='Task', related_name='task_file')
    file = models.FileField(verbose_name='Task file', max_length=256,
                            upload_to=task_file_path)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')


def queryset_approved(queryset):
    return queryset.filter(approved_at__isnull=False)


def queryset_rejected(queryset):
    return queryset.filter(rejected_at__isnull=False)


def queryset_verifying(queryset):
    return queryset.filter(approved_at__isnull=True,
                           rejected_at__isnull=True)


class ApprovedReportManager(models.Manager):
    def get_queryset(self):
        return queryset_approved(super().get_queryset())


class RejectedReportManager(models.Manager):
    def get_queryset(self):
        return queryset_rejected(super().get_queryset())


class VerifyingReportManager(models.Manager):
    def get_queryset(self):
        return queryset_verifying(super().get_queryset())


class Report(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='User')
    solution_text = models.TextField(verbose_name='Solution text')
    created_at = models.DateTimeField(verbose_name='Created at', auto_now_add=True)
    approved_at = models.DateTimeField(verbose_name='Approved at',
                                       null=True, blank=True, db_index=True)
    rejected_at = models.DateTimeField(verbose_name='Rejected at',
                                       null=True, blank=True, db_index=True)
    comment = models.TextField(verbose_name='Comment', null=True, blank=True)

    objects = models.Manager()
    approved_objects = ApprovedReportManager()
    rejected_objects = RejectedReportManager()
    verifying_objects = VerifyingReportManager()

    @property
    def status(self) -> str:
        if self.approved_at:
            return 'approved'
        elif self.rejected_at:
            return 'rejected'
        return 'verifying'

    @staticmethod
    def filtered_queryset() -> OrderedDict:
        return OrderedDict({
            'approved': queryset_approved,
            'rejected': queryset_rejected,
            'verifying': queryset_verifying,
        })

    @staticmethod
    def statuses() -> OrderedDict:
        return OrderedDict({
            'approved': Report.approved_objects,
            'rejected': Report.rejected_objects,
            'verifying': Report.verifying_objects,
        })

    def get_absolute_url(self) -> str:
        return reverse('pdf_report', args=(self.id,))

    class Meta:
        ordering = '-created_at',

    @property
    def username(self) -> str:
        return f'{self.user.last_name} {self.user.first_name}'

    def __str__(self) -> str:
        return f'{self.task} | {self.username}'


def report_file_path(report_file: 'ReportFile', filename: str) -> str:
    group = report_file.report.user.student_groups.first()
    return 'reports/{0}/{1}/{2}/{3}'.format(
        group.title if group else 'admin',
        report_file.report.task,
        report_file.report.username,
        filename
    )


class ReportFile(models.Model):
    report = models.OneToOneField(Report, on_delete=models.CASCADE,
                                  verbose_name='Report', related_name='report_file')
    file = models.FileField(verbose_name='Report file', max_length=256,
                            upload_to=report_file_path)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created at')


def source_report_path(file: 'SourceFile', filename: str) -> str:
    group = file.report.user.student_groups.first()
    return 'sources/{0}/{1}/{2}/{3}/{4}'.format(
        group.title if group else 'admin',
        file.report.username,
        file.report.task,
        timezone.now().strftime("%Y%m%d%H%M%S"),
        filename
    )


class SourceFile(models.Model):
    file = models.FileField(verbose_name='Source file', max_length=256,
                            upload_to=source_report_path)
    report = models.ForeignKey(Report, on_delete=models.CASCADE,
                               related_name='source_files', verbose_name='Report')

    def __str__(self) -> str:
        return f'{self.file.path} | {self.report}'


class ReportsSimilarity(models.Model):
    left = models.ForeignKey(Report, on_delete=models.CASCADE,
                             related_name='similarity_left', verbose_name='Left')
    right = models.ForeignKey(Report, on_delete=models.CASCADE,
                              related_name='similarity_right', verbose_name='Right')
    ratio = models.FloatField(verbose_name='Ratio')

    def __str__(self) -> str:
        return f'{self.left} <-> {self.right} | {self.ratio}'

report/forms.py
import os

from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from django.core.exceptions import ValidationError

from report import utils
from report.models import Report, Task


class TaskAdminForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'
        widgets = {
            'description': CKEditorUploadingWidget(),
        }


class ReportAdminForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = '__all__'
        widgets = {
            'solution_text': CKEditorUploadingWidget(),
            'comment': CKEditorUploadingWidget(),
        }


class ReportForm(forms.ModelForm):
    source_files = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'multiple': True}
    ))
    task = forms.ModelChoiceField(queryset=Task.get_enabled())

    def clean_source_files(self):
        for file in self.files.getlist('source_files'):
            if not utils.is_valid_filename_ext(os.path.splitext(file.name)[-1]):
                raise ValidationError(
                    'Попытка загрузить неподдерживаемый файл. '
                    'Загрузите файлы с исходным кодом: .cpp, .cs, .java и т.п.'
                )
        return self.cleaned_data['source_files']

    class Meta:
        model = Report
        fields = 'task', 'solution_text', 'source_files',
        widgets = {
            'solution_text': CKEditorUploadingWidget(),
        }

report/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView

from report.forms import ReportForm
from report.models import *
from report import tasks, utils


@login_required
def pdf_report_view(request, rid):
    if request.user.is_staff:
        report = get_object_or_404(Report, pk=rid)
    else:
        report = get_object_or_404(Report, pk=rid, user=request.user)

    try:
        return HttpResponse(report.report_file.file, content_type='application/pdf')

    except Exception:
        raise Http404()


@login_required
def report_view(request, rid: int):
    report = get_object_or_404(Report, pk=rid, user=request.user)
    return render(request, 'report/report.html', context={
        'report': report,
    })


class TasksView(LoginRequiredMixin, ListView):
    queryset = Task.get_enabled()
    template_name = 'report/tasks.html'


class ReportsView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'report/reports.html'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


@login_required
def pdf_task_view(request, tid: int):
    if request.user.is_staff:
        qs = Task
    else:
        qs = Task.get_enabled()

    task = get_object_or_404(qs, pk=tid)

    try:
        return HttpResponse(task.task_file.file, content_type='application/pdf')

    except Exception:
        raise Http404()


class SendReportView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('login')
    form_class = ReportForm
    template_name = 'report/send_report.html'
    report_id = None

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('source_files')
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user
            report.save()
            self.report_id = report.id
            for f in files:
                SourceFile.objects.create(file=f, report=report)
            tasks.generate_report_pdf.delay(report.id)
            tasks.check_uniqueness.delay(report.id)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse('report', args=(self.report_id,))


@staff_member_required
def reports_comparator_view(request, tid: int):
    report_src_id = request.GET.get('src')
    report_dst_id = request.GET.get('dst')

    report_src = get_object_or_404(Report, pk=report_src_id, task_id=tid)
    report_dst = get_object_or_404(Report, pk=report_dst_id, task_id=tid)

    ratio = utils.ratio_reports(report_src, report_dst)
    results = utils.compare_reports(report_src, report_dst)

    return render(request, 'report/comparator.html', context={
        'task': get_object_or_404(Task, pk=tid),
        'reports': Report.objects.filter(task_id=tid),
        'report_src_id': report_src.id,
        'report_dst_id': report_dst.id,
        'results': results,
        'ratio': ratio,
    })

report/templates/report/base.html
{% extends 'base.html' %}

{% block style %}
    <style>
        .nav {
            margin-top: 1em;
            margin-bottom: 2em;
        }

        .alert-danger {
            margin: 1em;
        }

        .alert-danger > ul {
            margin: 0;
        }
    </style>
{% endblock %}

{% block content %}
    <nav class="navbar navbar-light navbar-expand-md justify-content-between align-items-center nav">
        <div class="nav-item-panel">
            <a class="btn btn-light" href="{% url 'tasks' %}">Задачи</a>
            <a class="btn btn-light" href="{% url 'send_report' %}">Отправить отчёт</a>
            <a class="btn btn-light" href="{% url 'reports' %}">Мои отчёты</a>
        </div>
        <div class="nav-item-panel">
            <span>
                Привет, {{ user.get_full_name }}!
            </span>
            <a href="{% url 'password-change' %}" class="btn btn-info">Сменить пароль</a>
            {% if user.is_superuser %}
                <a href="{% url 'admin:index' %}" class="btn btn-primary">Панель администратора</a>
            {% endif %}
            <a href="{% url 'logout' %}" class="btn btn-info">Выйти</a>
        </div>
    </nav>

    {% block report %}{% endblock %}
{% endblock content %}

report/templates/report/comparator.html
{% extends 'report/base.html' %}

{% block style %}
    {{ block.super }}
    <style>
        h4 {
            margin-top: 1em;
        }

        .files {
            display: flex;
            flex-direction: column;
            align-content: center;
        }

        .diff-file {
            margin-top: 1em;
        }

        .diff-file:last-child {
            margin-bottom: 1em;
        }

        .diff-card {
            overflow-x: auto;
        }

        .diff {
            margin: 0 auto;
        }
    </style>
{% endblock %}

{% block title %}Простой diff{% endblock title %}

{% block report %}
    <h3 class="text-center">{{ task.title }}</h3>

    <form method="get" class="text-center">
        <div class="form-group">
            <select name="src" aria-label="src">
                {% for report in reports %}
                    <option {% if report.id == report_src_id %}selected{% endif %}
                            value="{{ report.id }}">
                        {{ report.created_at }} | {{ report.user.student_groups.first }} | {{ report.username }}
                    </option>
                {% endfor %}
            </select>
            <select name="dst" aria-label="dst">
                {% for report in reports %}
                    <option {% if report.id == report_dst_id %}selected{% endif %}
                            value="{{ report.id }}">
                        {{ report.created_at }} | {{ report.user.student_groups.first }} | {{ report.username }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <button class="btn btn-success mt-3" type="submit">Сравнить</button>
    </form>

    <h4 class="text-center">Максимальный коэффициент похожести: {{ ratio|floatformat:3 }}</h4>
{% endblock %}

{% block after_container %}
    <section class="files">
        {% for result in results %}
            <div class="diff-file">
                <h6 class="text-center">Коэффициент похожести: {{ result.0|floatformat:3 }}</h6>
                <div class="diff-card">{{ result.1|safe }}</div>
            </div>
        {% endfor %}
    </section>
{% endblock %}

report/templates/report/form_element.html
<div class="form-group">
    <label for="{{ field_id }}">{{ field_label }}</label>
    <div>{{ field }}</div>
    {% if field.errors %}
        <div class="alert alert-danger text-center" role="alert">
            {{ field.errors }}
        </div>
    {% endif %}
</div>

report/templates/report/password_change.html
{% extends 'report/base.html' %}

{% block title %}Сменить пароль{% endblock title %}

{% block report %}
    <div class="row justify-content-center">
        <form action="{% url 'password-change' %}" method="post" class="text-center">
            {% csrf_token %}

            {% include 'report/form_element.html' with field_id='id_old_password' field_label='Старый пароль' field=form.old_password %}
            {% include 'report/form_element.html' with field_id='id_new_password1' field_label='Новый пароль' field=form.new_password1 %}
            {% include 'report/form_element.html' with field_id='id_new_password2' field_label='Подтверждение нового пароля' field=form.new_password2 %}

            <button class="btn btn-success mt-3 self-align-center" type="submit">Сохранить</button>
        </form>
    </div>
{% endblock %}

report/templates/report/pdf_report_template.html
<!DOCTYPE html>

{% load report_filters %}

<html lang="ru">
    <head>
        <title>{{ report }}</title>
        <style>
            * {
                font-size: 100%;
                font-family: calibri, serif;
            }

            @page {
                margin: 1cm;
            }

            body {
                font-size: 16px;
            }

            section {
                page-break-before: always;
            }

            h2, h5, h6 {
                text-align: center;
            }

            .section_title {
                font-size: 20px;
                font-weight: bold;
                margin-bottom: 1em
            }

            pre {
                box-sizing: border-box;
                width: 100%;
                margin: 0;
                overflow-y: hidden;
                font-size: 12px;
                line-height: 20px;
                background: #efefef;
                border: 1px solid #777;
                padding: 10px;
                color: #333;
                overflow-x: auto;
                white-space: pre-wrap;
                white-space: -moz-pre-wrap !important;
                white-space: -o-pre-wrap;
                word-wrap: break-word;
            }
        </style>
    </head>

    <body>
        <section style="text-align: center">
            <p style="margin-top: 6mm">МИНИСТЕРСТВО ОБРАЗОВАНИЯ И НАУКИ РОССИЙСКОЙ ФЕДЕРАЦИИ</p>
            <p style="margin-top: 10mm">ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ АВТОНОМНОЕ<br>ОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ ВЫСШЕГО ОБРАЗОВАНИЯ</p>

            <p style="margin-top: 14mm">«Санкт-Петербургский национальный исследовательский университет<br>информационных технологий, механики и оптики»</p>
            <p style="margin-top: 10mm">Факультет информационных технологий и программирования</p>
            <p style="margin-top: 10mm">Кафедра информационных систем</p>

            <p style="margin-top: 26mm">Лабораторная работа №{{ report.task.number }}</p>
            <p style="margin-top: 2mm; font-weight: bold">{{ report.task.title }}</p>

            <p style="margin-top: 70mm; text-align: right">Выполнил студент группы {{ report.user.student_groups.first.title }}:</p>
            <p style="margin-top: 2mm; text-align: right">{{ report.username }}</p>

            <p style="margin-top: 50mm">САНКТ-ПЕТЕРБУРГ</p>
            <p style="margin-top: 4mm">{% now 'Y' %}</p>
        </section>

        <section>
            <h2 class="section_title">Задание</h2>
            {{ report.task.description|safe }}
        </section>

        <section>
            <h2 class="section_title">Ход рассуждений</h2>
            {{ report.solution_text|safe }}
        </section>

        {% for f in report.source_files.all %}
            <section>
                {% if forloop.first %}
                    <h2 class="section_title">Листинг</h2>
                {% endif %}
                <h2 style="font-weight: bold; margin-bottom: 1em">Файл {{ f.file.name|basename }}</h2>
                <pre style="width: 100%">{{ f.file|file_content }}</pre>
            </section>
        {% endfor %}
    </body>
</html>

report/templates/report/pdf_task_template.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>{{ task }}</title>
    </head>
    <body>
        <h2 style="text-align: center">Лабораторная работа {{ task.number }}</h2>
        <h1 style="text-align: center">{{ task.title }}</h1>
        {{ task.description|safe }}
    </body>
</html>

report/templates/report/report.html
{% extends 'report/base.html' %}
{% load report_filters %}

{% block title %}Отчёт | {{ report.task }} | {{ report.username }}{% endblock title %}

{% block report %}
    <div class="row justify-content-center">
        <div style="display: inline-block">
            <p><b>Задание:</b> {{ report.task }}</p>
            <p><b>Исполнитель:</b> {{ report.username }}</p>
            <p><b>Отчёт отправлен:</b> {{ report.created_at }}</p>
            <p><b>Статус:</b> {{ report.status|humanize_status }}</p>
        </div>
    </div>
{% endblock %}

report/templates/report/report_admin_form.html
{% extends 'admin/change_form.html' %}

{% block form_top %}
    {{ block.super }}
    {% if object_id %}
        <div class="submit-row">
            <a href="{% url 'pdf_report' object_id %}" target="_blank" rel="noreferrer noopener">Show preview</a>
            <input type="submit" value="Approve" name="_approve" style="background-color: forestgreen">
            <input type="submit" value="Approve without score" name="_approve_without_score" style="background-color: #5f8b24">
            <input type="submit" value="Reject" name="_reject" style="background-color: #ba2121">
        </div>
    {% endif %}
{% endblock %}

report/templates/report/reports.html
{% extends 'report/base.html' %}
{% load report_filters %}

{% block title %}Мои отчёты | {{ report.username }}{% endblock title %}

{% block report %}
    <h2 class="text-center">Мои отчёты</h2>

    <table class="table">
        <thead style="text-align: center;font-weight: bold">
        <tr>
            <td>Дата</td>
            <td>Работа</td>
            <td>Статус</td>
            <td>Просмотр</td>
            <td>Комментарий</td>
        </tr>
        </thead>
        <tbody>
        {% for report in object_list %}
            <tr style="background-color: {{ report.status|status2color }}">
                <td>{{ report.created_at }}</td>
                <td>{{ report.task }}</td>
                <td>{{ report.status|humanize_status }}</td>
                <td>
                    <a href="{{ report.get_absolute_url }}" target="_blank" rel="noopener noreferrer">
                        Открыть отчет
                    </a>
                </td>
                <td>{{ report.comment|default:''|safe }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

report/templates/report/send_report.html
{% extends 'report/base.html' %}

{% block style %}
    {{ block.super }}
    <style>
        #id_task {
            max-width: 100%;
        }
    </style>
{% endblock %}

{% block title %}Отправить отчёт{% endblock title %}

{% block report %}
    <h2 class="text-center">Отправить отчёт</h2>

    <form action="{% url 'send_report' %}" method="post" enctype="multipart/form-data" class="text-center">
        {% csrf_token %}
        {{ form.media }}

        {% include 'report/form_element.html' with field_id='id_task' field_label='Задание' field=form.task %}
        {% include 'report/form_element.html' with field_id='id_solution_text' field_label='Ход рассуждений' field=form.solution_text %}
        {% include 'report/form_element.html' with field_id='id_source_files' field_label='Исходные файлы' field=form.source_files %}

        <button class="btn btn-success mt-3" type="submit">Отправить</button>
    </form>
{% endblock %}

report/templates/report/tasks.html
{% extends 'report/base.html' %}

{% block title %}Задачи{% endblock title %}

{% block report %}
    <h2 class="text-center">Задачи</h2>

    {% for task in object_list %}
        <p>
            <a href="{{ task.get_absolute_url }}" target="_blank" rel="noopener noreferrer">
                Лабораторная работа {{ task.number }}. {{ task.title }}
            </a>
        </p>
    {% endfor %}
{% endblock %}